name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Cache Tauri dependencies
      uses: actions/cache@v3
      with:
        path: src-tauri/node_modules
        key: ${{ runner.os }}-tauri-${{ hashFiles('src-tauri/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-tauri-

    - name: Build with Tauri
      run: cargo tauri build --verbose
      working-directory: src-tauri

    - name: Run tests with Tauri
      run: cargo tauri test --verbose
      working-directory: src-tauri 
