name: Build Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 'stable'  # Use stable Rust toolchain
        components: 'rustfmt' # Add additional components if needed

    - name: Install System Dependencies
      run: |
        choco install -y \
          gtk-runtime \
          pkg-config \
          openssl \
          libsass \
          webkit2gtk

    - name: Cache Cargo and System Dependencies
      uses: actions/cache@v3
      with:
        path: |
          C:\Users\runneradmin\.cargo\registry
          C:\Users\runneradmin\.cargo\git
          C:\Users\runneradmin\.cargo\bin  # Cache the directory for Cargo-installed binaries
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('Install System Dependencies') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Build Tauri App
      run: cargo tauri build
