name: Build Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 'stable'  # Use stable Rust toolchain
        components: 'rustfmt' # Add additional components if needed

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          pkg-config \
          libssl-dev \
          libsoup2.4-dev \
          libjavascriptcoregtk-4.0-dev \
          libwebkit2gtk-4.0-dev \
          build-essential \
          curl

    - name: Cache Cargo and System Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin  # Cache the directory for Cargo-installed binaries
          /usr/lib/x86_64-linux-gnu
          /usr/include
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('Install System Dependencies') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Build Tauri App
      run: cargo tauri build