name: Build Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.68.0'  # Specify the Rust version required by your Tauri app
        components: 'rustfmt' # Add additional components if needed

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev pkg-config libssl-dev

    - name: Cache Cargo and Binaries
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin  # Cache the directory for Cargo-installed binaries
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Build Tauri App
      run: cargo tauri build
